seo: 
  site_name: Gaelle Garbani
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url: 'https://www.facebook.com/Gaelle-Garbani-105713318521709'
  twitter_username: 
design: 
  dark-text_color: '#395261'
  medium-text_color: 'rgb(57,82,97)'
  light-text_color: '#f7f5f3'
  featured-text_color: '#00afb9'
  dark_color: '#395261'
  medium_color: '#FFA995'
  light_color: '#f7f5f3'
  v-light_color: '#fff7f3'
  featured_color: '#00afb9'
  accent_color: 'rgb(167, 74, 74)'